### ISSUE TITLE
报错，如下：

### ISSUE THREAD

**Issue by lxy071130** [cssxsh/fix-protocol-version#14]
```java
E/fix-protocol-version: java.lang.NoSuchMethodError: 'java.util.Map net.mamoe.mirai.internal.utils.MiraiProtocolInternal$Companion.getProtocols$mirai_core()'
java.lang.NoSuchMethodError: 'java.util.Map net.mamoe.mirai.internal.utils.MiraiProtocolInternal$Companion.getProtocols$mirai_core()'
	at xyz.cssxsh.mirai.tool.FixProtocolVersion.info(FixProtocolVersion.kt:226)
	at xyz.cssxsh.mirai.tool.FixProtocolVersionPlugin.onEnable(FixProtocolVersionPlugin.kt:29)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:122)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:214)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
	at org.itxtech.mcl.Loader.start(Loader.java:128)
	at org.itxtech.mcl.Loader.main(Loader.java:53)
```
是版本问题吗？
```sh
> status
Running MiraiConsole v2.8.2, built on 2021-11-20 00:35:26.
Frontend Terminal: version 2.8.2, provided by Mamoe Technologies
```

**Comment by cssxsh** [comment]
> Running MiraiConsole v2.8.2, built on 2021-11-20 00:35:26.

?

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/commit/9b88868dc5fc1390cf7c24ca0f5d3b8537a7c5d0

你可以下载 CI 构建结果试试
