### ISSUE TITLE
2.15dev98+2.7.1无法登陆

### ISSUE THREAD

**Issue by Pika-Lee** [cssxsh/fix-protocol-version#20]
前两天还可以登陆，结果今天再登陆时就报235和16错误了。日志如下。

```
2023-06-18 12:21:59 I/main: Backend: version 2.15.0-dev-98, built on 2023-06-04 07:47:48.
2023-06-18 12:21:59 I/main: Frontend Terminal: version 2.15.0-dev-98, provided by Mamoe Technologies
2023-06-18 12:21:59 I/main: Welcome to visit https://mirai.mamoe.net/
2023-06-18 12:22:02 I/fix-protocol-version: 协议版本检查更新...
2023-06-18 12:22:03 I/fix-protocol-version: 注册服务...
2023-06-18 12:22:03 I/plugin: Successfully loaded plugin fix-protocol-version v1.7.1
2023-06-18 12:22:03 I/plugin: Successfully loaded plugin QRLogin v0.1.6
2023-06-18 12:22:04 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.10
2023-06-18 12:22:04 I/plugin: Successfully loaded plugin MiraiNative v2.0.0-cssxsh
2023-06-18 12:22:05 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-06-18 12:22:05 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE  8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_PAD    8.8.88.7083   2022-03-23T11:01:55+08:00
ANDROID_WATCH  2.0.8         2019-06-03T20:25:31+08:00
IPAD           8.9.33.614    2021-12-31T11:36:26+08:00
MACOS          6.7.9         1970-01-01T08:00+08:00

2023-06-18 12:22:05 W/QRLogin: 本插件仅在 2.15.0 或以上工作，且在正式版或先行发布版(RC)中可能无法使用
2023-06-18 12:22:05 I/MiraiNative: 正在加载 Mirai Native Bridge E:\mirai17\Mirai_2.15.0-M1\data\org.itxtech.mirainative\CQP.dll
2023-06-18 12:22:05 I/MiraiNative: 插件 com.5ogg.bilibili.dll 已被加载，返回值为 0 。
2023-06-18 12:22:06 I/main: 4 plugin(s) enabled.
2023-06-18 12:22:06 I/main: Auto-login 1845605751, protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
2023-06-18 12:22:06 I/MiraiNative: 插件 me.cqp.lyt.weiboMonitor.dll 已被加载，返回值为 0 。
2023-06-18 12:22:06 I/MiraiNative: 插件 me.cqp.mirai.help.dll 已被加载，返回值为 0 。
2023-06-18 12:22:07 I/Bot.1845605751: Loaded account secrets from local cache.
2023-06-18 12:22:08 I/TLV544Provider: t544 command: 810_a
2023-06-18 12:22:09 I/Bot.1845605751: Loaded account secrets from local cache.
2023-06-18 12:22:09 I/TLV544Provider: t544 command: 810_9
2023-06-18 12:22:09 I/Bot.1845605751: Calculating type 2 PoW, it can take some time....
2023-06-18 12:22:09 I/Bot.1845605751: Got PoW result, cost: 208 ms
2023-06-18 12:22:47 I/TLV544Provider: t544 command: 810_2
2023-06-18 12:22:50 I/Bot.1845605751: Loaded account secrets from local cache.
2023-06-18 12:22:50 E/main: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:242)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1845605751), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:469)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                ... 6 more
        Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(1845605751), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:507)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                ... 6 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1845605751), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )]

2023-06-18 12:22:50 I/Bot.1845605751: Bot cancelled: Bot closed
2023-06-18 12:22:51 V/Bot.1845605751: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@4b26b7
2023-06-18 12:22:51 I/main: mirai-console started successfully.`
```
麻烦大佬能解决一下登陆问题，感谢

**Comment by cssxsh** [comment]
> Fast login failed: Error(bot=Bot(...), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)

删掉登录缓存 `bots/.../`, 然后重新尝试登录

**Comment by Pika-Lee** [comment]
> > Fast login failed: Error(bot=Bot(...), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
> 
> 删掉登录缓存 `bots/.../`, 然后重新尝试登录

可以了，谢谢
