### ISSUE TITLE
加载jar后无调用启动bot出现报错

### ISSUE THREAD

**Issue by Cong0707** [cssxsh/fix-protocol-version#21]
java.util.ServiceConfigurationError: net.mamoe.mirai.internal.spi.EncryptService: Provider xyz.cssxsh.mirai.tool.TLV544Provider could not be instantiated                                                                                           at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)                                                     at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)                                 at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)                                         at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)                                                  at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1295)                                at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1328)                               at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1319)                                      at net.mamoe.mirai.utils.ServicesKt$loadServices$bothServices$1.invokeSuspend(Services.kt:92)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                             at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)                                           at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)                                         at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)                                        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)                                               at net.mamoe.mirai.spi.SpiServiceLoaderImpl.reloadAndSelect(SPIServiceLoader.kt:77)                                   at net.mamoe.mirai.spi.SpiServiceLoaderImpl.access$reloadAndSelect(SPIServiceLoader.kt:47)                            at net.mamoe.mirai.spi.SpiServiceLoaderImpl$_service$2.invoke(SPIServiceLoader.kt:66)                                 at net.mamoe.mirai.spi.SpiServiceLoaderImpl$_service$2.invoke(SPIServiceLoader.kt:64)                                 at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)                              at net.mamoe.mirai.spi.SpiServiceLoaderImpl.get_service(SPIServiceLoader.kt:64)                                       at net.mamoe.mirai.spi.SpiServiceLoaderImpl.getService(SPIServiceLoader.kt:56)                                        at net.mamoe.mirai.internal.spi.EncryptService$Companion.getInstance$mirai_core(EncryptService.kt:54)                 at net.mamoe.mirai.internal.network.protocol.packet.TlvKt.t544ForToken(Tlv.kt:974)                                    at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9$Password$1$1$1$1.invoke(WtLogin9.kt:138)                                                                                                                         at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9$Password$1$1$1$1.invoke(WtLogin9.kt:39)                                                                                                                          at net.mamoe.mirai.utils.TlvMapKt._writeTlvMap(TlvMap.kt:130)                                                         at net.mamoe.mirai.utils.TlvMapKt._writeTlvMap$default(TlvMap.kt:123)                                                 at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9$Password$1$1$1.invoke(WtLogin9.kt:39)                                                                                                                            at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9$Password$1$1$1.invoke(WtLogin9.kt:31)

**Comment by cssxsh** [comment]
检查是否 plugins 下有多个 fix-protocol-version
