### ISSUE TITLE
TIMEOUT

### ISSUE THREAD

**Issue by huanmeng-qwq** [cssxsh/fix-protocol-version#25]
使用`fix-protocol-version`出现timeout的情况, 不使用不会timeout
```shell
2023-06-29 14:34:12 V/Net QQ_ID: Invalidate caches because hash file not available.
2023-06-29 14:34:12 V/Net QQ_ID: No server list cached.
2023-06-29 14:34:14 D/Net QQ_ID: CAS: JustInitialized -> ProducerReady: true
2023-06-29 14:34:14 D/Net QQ_ID: CAS: ProducerReady -> Producing(deferred.completed=false): true
2023-06-29 14:34:14 I/Net QQ_ID: ECDH key is invalid, start to fetch ecdh public key from server.
2023-06-29 14:34:14 D/Net QQ_ID: CAS: Producing(deferred.completed=false) -> Consuming(value=null): true
2023-06-29 14:34:15 I/Net QQ_ID: Successfully fetched ecdh public key from server.
2023-06-29 14:34:15 V/Net QQ_ID: [AuthControl/acquire] Acquiring auth method
2023-06-29 14:34:15 D/Net QQ_ID: CAS: Consuming(value=Password@1876833741) -> Consumed(CompletableDeferredImpl{Active}@4039f435): true
2023-06-29 14:34:15 D/Net QQ_ID: [AuthControl/acquire] Authorization responded: Password@1876833741
2023-06-29 14:34:15 I/TLV544Provider: t544 command: 810_9 with ANDROID_PAD
2023-06-29 14:34:15 V/Net QQ_ID: Send: wtlogin.login(9:password-login)
2023-06-29 14:34:20 V/Net QQ_ID: Send: wtlogin.login(9:password-login)
2023-06-29 14:34:25 W/Net QQ_ID: Failed with auth method: Password@1876833741
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-06-29 14:34:25 V/Net QQ_ID: [AuthControl/resume] Fire auth failed with cause: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
2023-06-29 14:34:25 D/Net QQ_ID: CAS: Consumed(CompletableDeferredImpl{Active}@4039f435) -> ProducerReady: true
2023-06-29 14:34:25 D/Net QQ_ID: CAS: ProducerReady -> Producing(deferred.completed=false): true
2023-06-29 14:34:25 D/Net QQ_ID: CAS: Producing(deferred.completed=false) -> Consuming(value=null): true
2023-06-29 14:34:25 W/Net QQ_ID: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException

2023-06-29 14:34:25 I/Net QQ_ID: ECDH key is valid.
2023-06-29 14:34:25 V/Net QQ_ID: [AuthControl/acquire] Acquiring auth method
2023-06-29 14:34:25 D/Net QQ_ID: CAS: Consuming(value=null) -> Consumed(CompletableDeferredImpl{Active}@6e13c652): true
2023-06-29 14:34:25 D/Net QQ_ID: CAS: Consumed(CompletableDeferredImpl{Active}@6e13c652) -> Finished(Consumed(CompletableDeferredImpl{Active}@6e13c652), net.mamoe.mirai.utils.channels.ProducerFailureException: Producer failed to produce a value, see cause): true
2023-06-29 14:34:25 D/Net QQ_ID: [AuthControl/acquire] Authorization responded: Error[kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms]@653330922
2023-06-29 14:34:25 W/Net QQ_ID: Failed with auth method: Error[kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms]@653330922
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:262)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-06-29 14:34:25 W/Net QQ_ID: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:262)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        ... 6 more
        Suppressed: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
                at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
                at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
                at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
                at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: [CIRCULAR REFERENCE: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms]

2023-06-29 14:34:25 W/Net QQ_ID: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)
Exception in thread "main" [Debug] Bot cancelled: Bot closed
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:262)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
                at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
                at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
                at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
                at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: [CIRCULAR REFERENCE: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms]
```

**Comment by cssxsh** [comment]
1. 没有 fix-protocol-version 版本号
2. 没有 mirai 版本号

**Comment by huanmeng-qwq** [comment]
> 1. 没有 fix-protocol-version 版本号
> 2. 没有 mirai 版本号

fix-protocol-version 1.8.4
mirai 2.15.0-RC

**Comment by huanmeng-qwq** [comment]
ANDROID_PAD等协议都试过

**Comment by cssxsh** [comment]
换 Java 版本，用 17

**Comment by huanmeng-qwq** [comment]
```shell
C:\Bot>java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```
Java就是17版本

在不加载fix-protocol-version的情况下至少会抛出登录错误的异常信息，但是加载之后就只会抛出timeout的异常

**Comment by cssxsh** [comment]
换 open jdk

**Comment by cssxsh** [comment]
真的要论的话

你可以把 t544-enc-windows-x64.dll/t544-enc-windows-x86.dll 删了重新生成试试看
