### ISSUE TITLE
求助Failed to connect to /127.0.0.1:47914

### ISSUE THREAD

**Issue by zxmacc** [cssxsh/fix-protocol-version#27]
使用了[unidbg-fetch-qsign](https://github.com/cssxsh/fix-protocol-version/releases/tag/unidbg-fetch-qsign)后出现的问题
版本：
```
 10:06:14 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.70 from maven-stable
  10:06:15 [INFO] Verifying "net.mamoe:mirai-console" v2.15.0-RC from maven
  10:06:15 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.15.0-RC from maven
  10:06:15 [INFO] Verifying "net.mamoe:mirai-core-all" v2.15.0-RC from maven
  10:06:15 [INFO] Verifying "net.mamoe:mirai-api-http" v2.9.1 from maven
  10:06:16 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1 from maven-stable
  10:06:16 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.2.0 from maven
  10:06:16 [INFO] Verifying "net.mamoe:chat-command" v0.6.0 from maven-stable
  10:06:16 [INFO] Verifying "org.apache.logging.log4j:log4j-to-slf4j" v2.20.0 from maven-stab
2023-07-01 10:06:17 I/main: Backend: version 2.15.0-sign, built on 2023-06-23 00:42:57.
2023-07-01 10:06:17 I/main: Frontend Terminal: version 2.15.0-sign, provided by Mamoe Technologies
```

服务器CPU: [ "Intel(R) Xeon(R) CPU E5-26xx v4 2 Physical Core" ] 
系统: ubuntu-22.04 [x86_64]

出现的问题：
```
2023-07-01 10:06:42 I/TLV544Provider: server start http://127.0.0.1:47914
2023-07-01 10:09:44 I/Bot.1992588307: Bot cancelled: Bot closed
2023-07-01 10:09:44 E/main: java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to /127.0.0.1:47914
java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to /127.0.0.1:47914
        at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
        at fix-protocol-version-1.8.5-dev.mirai2.jar//xyz.cssxsh.mirai.tool.TLV544Provider.server(TLV544Provider.kt:155)
        at fix-protocol-version-1.8.5-dev.mirai2.jar//xyz.cssxsh.mirai.tool.TLV544Provider.initialize(TLV544Provider.kt:188)
        at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.kt:122)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)

        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.ConnectException: Failed to connect to /127.0.0.1:47914
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 18 more
2023-07-01 10:09:44 V/Bot.1992588307: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@139a4eb2
2023-07-01 10:09:44 I/main: mirai-console started successfully.
```

请求大佬帮助

**Comment by cssxsh** [comment]
unidbg-fetch-qsign 文件夹底下有日志文件
