### ISSUE TITLE
unidbg-fetch-qsign 23-07-01.V1.1.0版本登录时报错但是能成功登录，登录后只能接收消息，所有插件无反应

### ISSUE THREAD

**Issue by Natsukage** [cssxsh/fix-protocol-version#31]
环境：
Windows 2019
Mirai 2.15.0-RC
fix-protocol-version unidbg-fetch-qsign 23-07-01.V1.1.0

已经按照使用说明覆盖了
```
./libs
./plugins/fix-protocol-version-1.8.5-dev.mirai2.jar
./unidbg-fetch-qsign-1.1.0
```
文件夹，并删除了旧版本文件。

由于MiraiNative需求32位Java，所以通过位于mirai路径下（`D:\mirai\java\bin\java.exe`）的32位Java启动mirai
系统中已经安装64位Java17（jdk-17_windows-x64_bin）位于`C:\Program Files\Java\jdk-17\`，并且为默认的java路径
```
C:\Users\Administrator>java -version
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)
```
start.cmd的文件内容如下（只改动了set JAVA_BINARY="D:\mirai\java\bin\java.exe"这一行）
```
@echo off
setlocal
set JAVA_BINARY="D:\mirai\java\bin\java.exe"
if exist "java-home" set JAVA_BINARY=".\java-home\bin\java.exe"

%JAVA_BINARY% -version
%JAVA_BINARY% -jar mcl.jar %*

set EL=%ERRORLEVEL%
if %EL% NEQ 0 (
    echo Process exited with %EL%
    pause
)
```

启动mirai过程中会有一个`E/TLV544Provider: qSecurityGetSign`的报错，如下（QQ号已被替换为123456789），报错为`500 Internal Server Error. Text: ""`

```
2023-07-02 18:39:39 I/main: Auto-login 123456789, protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
2023-07-02 18:39:40 I/Bot.123456789: Loaded account secrets from local cache.
2023-07-02 18:39:40 I/TLV544Provider: sign server start, log file:///D:/mirai/./unidbg-fetch-qsign-1.1.0/123456789.8379.log
2023-07-02 18:39:48 I/TLV544Provider: sign server ready, url http://127.0.0.1:8379
2023-07-02 18:39:48 I/TLV544Provider: t544 command: 810_a
2023-07-02 18:39:48 I/TLV544Provider: sign command: wtlogin.exchange_emp with V1_AND_SQ_8.9.58_4106_YYB_D
2023-07-02 18:39:52 E/TLV544Provider: qSecurityGetSign<123456789>
java.util.concurrent.ExecutionException: io.ktor.client.plugins.ServerResponseException: Server error(GET http://127.0.0.1:8379/sign?uin=123456789&qua=V1_AND_SQ_8.9.58_4106_YYB_D&cmd=wtlogin.exchange_emp&seq=54990&buffer=0204E61F4108100001CF9B352E03070000000002000000000000000002016F605E732A979DA0CBCD28412BA20E9401310002004104EBF7A1AA553CC9D6DF4A592C3F7B8FE8DB151009F7F3E79F88B3F0803DB51F184A999665D6E59E137CB3CC439410ADDEF43C1C50D747C1EB836B2A5982F63C5856334890C84D842BB9F8B2CED24713EC3E922FA3C9D1B0122960DE253E2FD1B26B7364E677ADFCAB7847E879FB5F52E850413D244EDA97037FC9E5CE13F53E1D53E7BEE575E7063DFA7F4489A3F677791AA8374EF39F95931F258295803AD222B20C2398A6E3D19DEFD1995F8C4278547FE39A06D5A508254553024FAA715C572DECA97B3B145E918943EF8CCA8F864E3A08ED774908E240B88CC9D6E07CDB614060BD967E044B510FC1AA5F626092796BCABA37771394F0CFEB2B3F9B6A44AFEAE40B60D988F86BA4BBD10250FAB13701826B451D92DF342EF69737B4594398DE86B6C49CD48B3EE4D652969E2E91D028A2910258896E7C0840DA6C05CCE66F5EA0A40C3C9E2B3ED9E57118391A59587BC311443F72D5F2D08BB451582BCA31FA30042D8E6F1D1CB3AEC8C4311B407F66B6B78AB7FA33893D8E04C995FAA6655BE83602F2B52608E072771EF1C46A651AC23C0B0781FE9D55BB36BCC0B1609B9D54B98DBCD845EE6A00E84F77716163C1FDBFA50D887D179F1D596BC28D23F22BE039D1C1E2A549217701065BC41CF2B5B6F63440231F0BDF2B7E4BB16EC2A44D47725DF5F7044791DE0CCDACE4AFD5B2C7D4394018B54D37EA16616B704D5496219FDB1E25DE307606B8F278E1292EB179267C574D1C5F19D59353C9E28A424F65A0FFADAE7C3D1130E71D23C780122E6324D609369130832D357840C159DD4E7CC9F7F2F4078B9F39406D6DC97480B26BC25323F391BB6144F60579CFCA99A75C5
[123456789.8379.error.log](https://github.com/cssxsh/fix-protocol-version/files/11929307/123456789.8379.error.log)
[123456789.8379.log](https://github.com/cssxsh/fix-protocol-version/files/11929308/123456789.8379.log)
30E6494636EB1FDF33828C74E7761424389CEC5D3465F617AE98D06C9C5D3FF675F7E5FEAA250C2E2A8C7EDF4378AAC1AD48E96007F1E656E37E3A86B4C868993DBEC5EA0ACB1C5783DE75DC770CD551136F2DE02431A4F481FE2A4D4FA9B1D92B84CDFF9E4474E2AADB8CE0F52CD3BEA9FA60B6DC2AC860E0DF6CC21C6C90EAF544AAE523A398ECB0DF15734F76542044F77C7EAC6939AF2A1E6C591E44C1260AA44984EB84231A4762A4CF2DFEAB56AAB5255E062849F139C37A96590DE98365F7BC8E0977D2A4BA4C0540B8570F13B6AF4F27B49163C83A5DC100A70ACE10A7F84AE156409A43C683757556C731FD165455CDB9A6A0CBB0C9F33276C4730D2264A29A6C01C24E17C618C7BE88513514EEBB2CE3CF5A8C40ADE90DD8DFE49ED0280F191DD5905909071A2626C73FFEC089455D1475451379479FC40329634A41E0FC2EFF427590460364B8102219A0913C6345C2E5D4A4931D383FFBD66FE73A40DE22C6E9A747E3648A3952BC100057BFCEAF7EF5BF2F79E20C152A5871237B3D1EEC94EEE7FCA092500F75B1C8B1B196F39C4D9005108983271E2041BC1605B572974D9DACB6515B174DB8188BDDF50F6A30C72B94CDB2526CC2CBAD350908B6F2BB4A9C06373B9F8D3513D8CC22ADAC7A48F1A9EDFB4611F3A3431EB110DA361ACF8BC50486E30718FBDE4E2CF171855EBA510008C9AD7B0FBF2284892ABF58BFEAF7BCBD471E9863A515F94E192F9C3D6A14FB7AED44830B5951CE0EFF50F444188831A7F2D2F296E955D6C4350118E6AF3CCAC346820ABE0A209B7BFDFA5EFF750A919E7889F24A7EAEB03: 500 Internal Server Error. Text: ""
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at fix-protocol-version-1.8.5-dev.mirai2.jar//xyz.cssxsh.mirai.tool.TLV544Provider.qSecurityGetSign(TLV544Provider.kt:233)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin10$invoke$1.invoke(WtLogin10.kt:122)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin10$invoke$1.invoke(WtLogin10.kt:32)
	at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildLoginOutgoingPacket(OutgoingPacket.kt:305)
	at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildLoginOutgoingPacket$default(OutgoingPacket.kt:273)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin10.invoke(WtLogin10.kt:32)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin10.invoke$default(WtLogin10.kt:27)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:527)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.doFastLogin$suspendImpl(SsoProcessor.kt:179)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.doFastLogin(SsoProcessor.kt)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:230)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: io.ktor.client.plugins.ServerResponseException: Server error(GET http://127.0.0.1:8379/sign?uin=123456789&qua=V1_AND_SQ_8.9.58_4106_YYB_D&cmd=wtlogin.exchange_emp&seq=54990&buffer=0204E61F4108100001CF9B352E03070000000002000000000000000002016F605E732A979DA0CBCD28412BA20E9401310002004104EBF7A1AA553CC9D6DF4A592C3F7B8FE8DB151009F7F3E79F88B3F0803DB51F184A999665D6E59E137CB3CC439410ADDEF43C1C50D747C1EB836B2A5982F63C5856334890C84D842BB9F8B2CED24713EC3E922FA3C9D1B0122960DE253E2FD1B26B7364E677ADFCAB7847E879FB5F52E850413D244EDA97037FC9E5CE13F53E1D53E7BEE575E7063DFA7F4489A3F677791AA8374EF39F95931F258295803AD222B20C2398A6E3D19DEFD1995F8C4278547FE39A06D5A508254553024FAA715C572DECA97B3B145E918943EF8CCA8F864E3A08ED774908E240B88CC9D6E07CDB614060BD967E044B510FC1AA5F626092796BCABA37771394F0CFEB2B3F9B6A44AFEAE40B60D988F86BA4BBD10250FAB13701826B451D92DF342EF69737B4594398DE86B6C49CD48B3EE4D652969E2E91D028A2910258896E7C0840DA6C05CCE66F5EA0A40C3C9E2B3ED9E57118391A59587BC311443F72D5F2D08BB451582BCA31FA30042D8E6F1D1CB3AEC8C4311B407F66B6B78AB7FA33893D8E04C995FAA6655BE83602F2B52608E072771EF1C46A651AC23C0B0781FE9D55BB36BCC0B1609B9D54B98DBCD845EE6A00E84F77716163C1FDBFA50D887D179F1D596BC28D23F22BE039D1C1E2A549217701065BC41CF2B5B6F63440231F0BDF2B7E4BB16EC2A44D47725DF5F7044791DE0CCDACE4AFD5B2C7D4394018B54D37EA16616B704D5496219FDB1E25DE307606B8F278E1292EB179267C574D1C5F19D59353C9E28A424F65A0FFADAE7C3D1130E71D23C780122E6324D609369130832D357840C159DD4E7CC9F7F2F4078B9F39406D6DC97480B26BC25323F391BB6144F60579CFCA99A75C530E6494636EB1FDF33828C74E7761424389CEC5D3465F617AE98D06C9C5D3FF675F7E5FEAA250C2E2A8C7EDF4378AAC1AD48E96007F1E656E37E3A86B4C868993DBEC5EA0ACB1C5783DE75DC770CD551136F2DE02431A4F481FE2A4D4FA9B1D92B84CDFF9E4474E2AADB8CE0F52CD3BEA9FA60B6DC2AC860E0DF6CC21C6C90EAF544AAE523A398ECB0DF15734F76542044F77C7EAC6939AF2A1E6C591E44C1260AA44984EB84231A4762A4CF2DFEAB56AAB5255E062849F139C37A96590DE98365F7BC8E0977D2A4BA4C0540B8570F13B6AF4F27B49163C83A5DC100A70ACE10A7F84AE156409A43C683757556C731FD165455CDB9A6A0CBB0C9F33276C4730D2264A29A6C01C24E17C618C7BE88513514EEBB2CE3CF5A8C40ADE90DD8DFE49ED0280F191DD5905909071A2626C73FFEC089455D1475451379479FC40329634A41E0FC2EFF427590460364B8102219A0913C6345C2E5D4A4931D383FFBD66FE73A40DE22C6E9A747E3648A3952BC100057BFCEAF7EF5BF2F79E20C152A5871237B3D1EEC94EEE7FCA092500F75B1C8B1B196F39C4D9005108983271E2041BC1605B572974D9DACB6515B174DB8188BDDF50F6A30C72B94CDB2526CC2CBAD350908B6F2BB4A9C06373B9F8D3513D8CC22ADAC7A48F1A9EDFB4611F3A3431EB110DA361ACF8BC50486E30718FBDE4E2CF171855EBA510008C9AD7B0FBF2284892ABF58BFEAF7BCBD471E9863A515F94E192F9C3D6A14FB7AED44830B5951CE0EFF50F444188831A7F2D2F296E955D6C4350118E6AF3CCAC346820ABE0A209B7BFDFA5EFF750A919E7889F24A7EAEB03: 500 Internal Server Error. Text: ""
	at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:55)
	at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
	at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43)
	at fix-protocol-version-1.8.5-dev.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 5 more

2023-07-02 18:39:53 I/Bot.123456789: Saved account secrets to local cache for fast login.
2023-07-02 18:39:53 I/Bot.123456789: Login successful.
2023-07-02 18:39:56 V/Bot.123456789: Event: BotOnlineEvent(bot=Bot(123456789))
2023-07-02 18:39:56 I/Bot.123456789: Bot login successful.
2023-07-02 18:39:56 V/Bot.123456789: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Success@1e03fe4
2023-07-02 18:39:56 I/MiraiNative: Mirai Native 正启用所有插件。
2023-07-02 18:39:56 I/main: mirai-console started successfully.
```
然后正常登录，登录后mirai控制台似乎可以正常收到所有消息，但是所有的插件（包括mirai下原生的petpet，MiraiNative运行的Dice!与MAH作为桥接的外部插件）皆无反应。当我在群聊中打出指令后，Bot从日志中可以看到收到了消息，但是完全没有发送的回应（哪怕是发问号时回叹号的复读机这种都不行）
如果是风控的话，一般应该是Mirai控制台显示发送了消息，但是实际QQ中没有收到，但是现在的情况是正常收到了消息，但是Bot所有类型的插件全都无法正常处理。
unidbg-fetch-qsign-1.1.0目录下的日志文件中也有大量警告，不确定具体原因。但是看起来似乎unidbg-fetch-qsign没有正常工作。
[123456789.8379.log](https://github.com/cssxsh/fix-protocol-version/files/11929314/123456789.8379.log)
[123456789.8379.error.log](https://github.com/cssxsh/fix-protocol-version/files/11929313/123456789.8379.error.log)

unidbg-fetch-qsign应该是正常工作在64位Java17下的，否则错误日志会直接提示
`Can't load IA 32-bit .dll on a AMD 64-bit platform`
最开始我就是因为这个原因所以特地重装了64位Java17，现在没有这样的报错了，但是却出现了上述的情况

想问一下这个有可能是什么原因呢？辛苦了，万分感谢！

**Comment by cssxsh** [comment]
500 Internal Server Error.

unidbg-fetch-qsign
签名服务的问题
