### ISSUE TITLE
1.9.4配合unidbg-fetch-qsign时会出现Request timeout to 127.0.0.1/127.0.0.1:9090

### ISSUE THREAD

**Issue by Natsukage** [cssxsh/fix-protocol-version#46]
Mirai 2.15.0正式版
fix-protocol-version 1.9.4
unidbg-fetch-qsign 1.1.3
Windows 2019
mirai刚启动后一段时间内可以正常运行，一段时间后，每当发送消息或图片时，mirai侧都会报错
```
2023-07-11 21:39:45 I/stdout: 发送图片时出错：java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:9090 after 30000 ms
2023-07-11 21:39:45 W/stderr: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:9090 after 30000 ms
2023-07-11 21:39:45 W/stderr: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
2023-07-11 21:39:45 W/stderr: 	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.sign(UnidbgFetchQsign.kt:162)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.qSecurityGetSign(UnidbgFetchQsign.kt:129)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildRawUniPacket(OutgoingPacket.kt:139)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbSendMsg.createToGroupImpl$mirai_core(MessageSvc.PbSendMsg.kt:744)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbSendMsgKt.createToGroup(MessageSvc.PbSendMsg.kt:585)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage$suspendImpl(MessageProtocolStrategy.kt:150)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:139)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:66)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:361)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:345)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:221)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.contact.Group$sendMessage$1.invoke(Group.kt)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.contact.Group$sendMessage$1.invoke(Group.kt)
2023-07-11 21:39:45 W/stderr: 	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
2023-07-11 21:39:45 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-11 21:39:45 W/stderr: 	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
2023-07-11 21:39:45 W/stderr: 	at me.him188.kotlin.jvm.blocking.bridge.internal.RunSuspendKt.$runSuspend$(RunSuspend.kt:18)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
2023-07-11 21:39:45 W/stderr: 	at petpet-5.4.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetService.sendImage(MiraiPetService.java:145)
2023-07-11 21:39:45 W/stderr: 	at petpet-5.4.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.responseMessage(MiraiPetpet.java:324)
2023-07-11 21:39:45 W/stderr: 	at petpet-5.4.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.onGroupMessage(MiraiPetpet.java:142)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:600)
2023-07-11 21:39:45 W/stderr: 	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:600)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2023-07-11 21:39:45 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-07-11 21:39:45 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-07-11 21:39:45 W/stderr: Caused by: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:9090 after 30000 ms
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
2023-07-11 21:39:45 W/stderr: 	at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-07-11 21:39:45 W/stderr: 	at java.base/java.lang.Thread.run(Unknown Source)
```
同时unidbg-fetch-qsign侧没有收到请求的日志。
此时不重启unidbg-fetch-qsign，直接重启mirai，bot恢复正常。unidbg-fetch-qsign端也会出现新的日志。
但是经过一段时间后，又会出现此情况。

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/discussions/45
