### ISSUE TITLE
安装最新版本之后依然无法识别,大佬知道是什么情况嘛,下面是错误报告

### ISSUE THREAD

**Issue by Muziyun0010** [cssxsh/fix-protocol-version#5]
23:41:16 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  23:41:16 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.6 (arch: 64)
  23:41:16 [INFO] https://github.com/iTXTech/mirai-console-loader
  23:41:16 [INFO] This program is licensed under GNU AGPL v3
  23:41:17 [ERROR] Failed to fetch announcement for "xyz.cssxsh.mirai:fix-protocol-version"<==这里
  23:41:17 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  23:41:17 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0
  23:41:18 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0
  23:41:18 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0
  23:41:18 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  23:41:19 [INFO] Verifying "net.mamoe:mirai-api-http" v2.9.1
  23:41:19 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3
  23:41:19 [INFO] Verifying "xyz.cssxsh.mirai:fix-protocol-version"
  23:41:19 [ERROR] Failed to verify package "xyz.cssxsh.mirai:fix-protocol-version"<==还有这里
  23:41:19 [ERROR] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395)
        at com.google.gson.Gson.fromJson(Gson.java:1214)
        at com.google.gson.Gson.fromJson(Gson.java:1124)
        at com.google.gson.Gson.fromJson(Gson.java:1034)
        at com.google.gson.Gson.fromJson(Gson.java:1001)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:84)
        at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:117)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:190)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:190)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384)
        ... 13 more

**Comment by cssxsh** [comment]
? 你在干什么
我在哪里说过他支持MCL安装
