### ISSUE TITLE
从2.15.0-RC1升级至2.15.0之后，出现NoSuchMethodError

### ISSUE THREAD

**Issue by anshangPro** [cssxsh/fix-protocol-version#53]
## 运行环境

- Windows 11
- Android项目Junit测试
- 使用依赖
```
    plugins {
        id 'com.android.application'
        id 'org.jetbrains.kotlin.android'
        id 'kotlin-kapt'
    }

    def mirai_version = '2.15.0'
    implementation 'org.asynchttpclient:async-http-client:2.12.3'
    implementation files('libs/fix-protocol-version-1.9.5.mirai2.jar')
    implementation "net.mamoe:mirai-core:$mirai_version"
    implementation "net.mamoe:mirai-core-utils:$mirai_version"
    implementation "net.mamoe:mirai-core-api:$mirai_version"
```

## 运行代码
`FixProtocolVersion.update()`

## 报错信息
```
'java.util.Map net.mamoe.mirai.internal.utils.MiraiProtocolInternal$Companion.getProtocols$mirai_core()'
java.lang.NoSuchMethodError: 'java.util.Map net.mamoe.mirai.internal.utils.MiraiProtocolInternal$Companion.getProtocols$mirai_core()'
	at xyz.cssxsh.mirai.tool.FixProtocolVersion.update(FixProtocolVersion.kt:79)
	at live.anshang.tq.MiraiFunctionTest.qSignTest(MiraiFunctionTest.kt:45)
```

**Comment by cssxsh** [comment]
个人估计是函数签名的问题，你可以自行检查一下签名是不是变了

**Comment by cssxsh** [comment]
```kotlin
        MiraiProtocolInternal.Companion::class.java.methods.forEach {
            println(it.name)
        }
```
