### ISSUE TITLE
访问api超时

### ISSUE THREAD

**Issue by 0xiaoshenap** [cssxsh/fix-protocol-version#54]
MCL启动命令
export JAVA_BINARY=java
$JAVA_BINARY -Dxyz.cssxsh.mirai.tool.ViVo50.Session.timeout=600000 -jar mcl.jar $*

2023-07-14 03:58:20 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///root/mcl/KFCFactory.json)
2023-07-14 03:58:20 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-07-14 03:58:20 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-07-14 03:58:20 W/EncryptService.alert: Service details:
2023-07-14 03:58:20 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-07-14 03:58:20 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.9.5.mirai2.jar}
2023-07-14 03:58:20 W/EncryptService.alert:   `- Source: file:/root/mcl/plugins/fix-protocol-version-1.9.5.mirai2.jar
2023-07-14 03:58:20 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/root/mcl/plugins/fix-protocol-version-1.9.5.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.9.5.mirai2.jar}
 <no principals>
 java.security.Permissions@6156a93c (
 ("java.io.FilePermission" "/root/mcl/plugins/fix-protocol-version-1.9.5.mirai2.jar" "read")
)

2023-07-14 03:58:23 I/UnidbgFetchQsign: Bot(1036474463) initialize by http://127.0.0.1:18080
Login failed: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:18080 after 30000 ms
2023-07-14 03:58:54 E/console: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:18080 after 30000 ms
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:18080 after 30000 ms
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
        at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.register(UnidbgFetchQsign.kt:69)
        at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.initialize(UnidbgFetchQsign.kt:52)
        at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.kt:123)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:18080 after 30000 ms
        at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
        at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
        at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-07-14 03:58:54 I/Bot.1036474463: Bot cancelled: Bot closed

**Comment by cssxsh** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/issues/120

**Comment by cssxsh** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/issues/126
