### ISSUE TITLE
似乎无法正确读取配置文件的键名

### ISSUE THREAD

**Issue by kaixinol** [cssxsh/fix-protocol-version#58]
签名服务器：`./bin/unidbg-fetch-qsign  --basePath=txlib\8.9.63`
- `config.json`：
```json
{
  "server": {
    "host": "127.0.0.1",
    "port": 8080
  },
  "key": "114514",
  "auto_register": false,
  "reload_interval": 40,
  "protocol": {
    "qua": "V1_AND_SQ_8.9.63_4194_YYB_D",
    "version": "8.9.63",
    "code": "4194"
  },
  "unidbg": {
    "dynarmic": false,
    "unicorn": true,
    "debug": false
  }
}
```

- `C:\Users\Administrator\Desktop\KFCFactory.json`:
```json
{
    "8.9.63": {
        "base_url": "http://127.0.0.1:8080",
        "type": "fuqiuluo/unidbg-fetch-qsign",
        "key": "114514"
    }
}
```
报错：

```log
2023-07-18 15:55:30 I/main: Backend: version 2.15.0, built on 2023-07-11 04:57:17.
2023-07-18 15:55:30 I/main: Frontend Terminal: version 2.15.0, provided by Mamoe Technologies
2023-07-18 15:55:30 I/main: Welcome to visit https://mirai.mamoe.net/
2023-07-18 15:55:36 I/fix-protocol-version: 协议版本检查更新...
2023-07-18 15:55:36 I/fix-protocol-version: 注册服务...
2023-07-18 15:55:36 I/fix-protocol-version: 服务配置文件 file:///C:/Users/Administrator/Desktop/KFCFactory.json
2023-07-18 15:55:36 I/plugin: Successfully loaded plugin fix-protocol-version v1.9.6
2023-07-18 15:55:36 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-07-18 15:55:36 I/QRLogin: Loading QRLogin v0.1.9
2023-07-18 15:55:36 W/QRLogin: 本插件仅在 2.15.0 或以上工作，且在正式版或先行发布版(RC)中可能无法使用
2023-07-18 15:55:36 I/plugin: Successfully loaded plugin QRLogin v0.1.9
2023-07-18 15:55:38 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.11
2023-07-18 15:55:38 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-07-18 15:55:38 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-07-18 15:55:38 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE  8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_PAD    8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_WATCH  2.0.8         2019-06-03T20:25:31+08:00
IPAD           8.9.50.611    2023-02-16T15:10:14+08:00
MACOS          6.8.2.21241   2022-03-14T11:11:35+08:00

2023-07-18 15:55:39 I/Mirai HTTP API: ********************************************************
2023-07-18 15:55:39 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2023-07-18 15:55:39 I/MahKtorAdapter[http]: Application started in 0.473 seconds.
2023-07-18 15:55:39 I/MahKtorAdapter[http]: Responding at http://127.0.0.1:8088
2023-07-18 15:55:39 I/http adapter: >>> [http adapter] is listening at http://127.0.0.1:8088
2023-07-18 15:55:39 I/MahKtorAdapter[ws]: Autoreload is disabled because the development mode is off.
2023-07-18 15:55:39 I/MahKtorAdapter[ws]: Application started in 0.094 seconds.
2023-07-18 15:55:39 I/MahKtorAdapter[ws]: Responding at http://127.0.0.1:8087
2023-07-18 15:55:39 I/ws adapter: >>> [ws adapter] is listening at ws://127.0.0.1:8087
2023-07-18 15:55:39 I/Mirai HTTP API: Http api server is running with verifyKey: ServiceVerifyKey
2023-07-18 15:55:39 I/Mirai HTTP API: adaptors: [http,ws]
2023-07-18 15:55:39 I/Mirai HTTP API: ********************************************************
2023-07-18 15:55:39 I/QRLogin: 正在启用插件 QRLogin v0.1.9
2023-07-18 15:55:39 I/QRLogin: Mirai 版本: 2.15.0
2023-07-18 15:55:40 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-07-18 15:55:40 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-07-18 15:55:40 I/main: 5 plugin(s) enabled.
2023-07-18 15:55:40 I/main: Auto-login 2634732881, protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
2023-07-18 15:55:40 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///C:/Users/Administrator/Desktop/KFCFactory.json)
2023-07-18 15:55:40 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-07-18 15:55:40 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-07-18 15:55:40 W/EncryptService.alert: Service details:
2023-07-18 15:55:40 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-07-18 15:55:40 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.9.6.mirai2.jar}
2023-07-18 15:55:40 W/EncryptService.alert:   `- Source: file:/C:/Users/Administrator/Desktop/plugins/fix-protocol-version-1.9.6.mirai2.jar
2023-07-18 15:55:40 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/C:/Users/Administrator/Desktop/plugins/fix-protocol-version-1.9.6.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.9.6.mirai2.jar}
 <no principals>
 java.security.Permissions@304068 (
 ("java.io.FilePermission" "C:\Users\Administrator\Desktop\plugins\fix-protocol-version-1.9.6.mirai2.jar" "read")
)


2023-07-18 15:55:41 E/main: java.util.NoSuchElementException: 没有找到对应 8.9.58 的服务配置，file:///C:/Users/Administrator/Desktop/KFCFactory.json
java.util.NoSuchElementException: 没有找到对应 8.9.58 的服务配置，file:///C:/Users/Administrator/Desktop/KFCFactory.json
        at fix-protocol-version-1.9.6.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:77)
        at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
        at net.mamoe.mirai.internal.QQAndroidBot.getComponents(QQAndroidBot.kt:189)
        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:154)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:426)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:369)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
        Suppressed: java.util.NoSuchElementException: 没有找到对应 8.9.58 的服务配置，file:///C:/Users/Administrator/Desktop/KFCFactory.json
                at fix-protocol-version-1.9.6.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:77)
                at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
                at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
                at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
                at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
                at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
                at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
                at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
                at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
                at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
                at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
                at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
                at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)
                at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.access$getScope(SelectorNetworkHandler.kt:45)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection$suspendImpl(SelectorNetworkHandler.kt:130)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection(SelectorNetworkHandler.kt)
                at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:145)
                ... 27 more

2023-07-18 15:55:41 I/Bot.2634732881: Bot cancelled: Job was cancelled
2023-07-18 15:55:41 E/Bot.2634732881: java.util.NoSuchElementException: 没有找到对应 8.9.58 的服务配置，file:///C:/Users/Administrator/Desktop/KFCFactory.json
java.util.NoSuchElementException: 没有找到对应 8.9.58 的服务配置，file:///C:/Users/Administrator/Desktop/KFCFactory.json
        at fix-protocol-version-1.9.6.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:77)
        at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:112)
        at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:65)
        at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:59)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1392)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
        at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:183)
        at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:122)
        at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:98)
        at net.mamoe.mirai.Bot.close(Bot.kt:188)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:433)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:369)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)

2023-07-18 15:55:41 E/main: Failed to init MiraiConsole.
java.util.NoSuchElementException: 没有找到对应 8.9.58 的服务配置，file:///C:/Users/Administrator/Desktop/KFCFactory.json
        at fix-protocol-version-1.9.6.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:77)
        at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:112)
        at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:118)
        at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:98)
        at net.mamoe.mirai.Bot.close(Bot.kt:188)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:433)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:369)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
```

**Comment by cssxsh** [comment]
> 2023-07-18 15:55:38 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE  8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_PAD    8.9.58.11170  2023-05-19T11:35+08:00

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/issues/2740
