### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.String io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim

### ISSUE THREAD

**Issue by ZZM-user** [cssxsh/fix-protocol-version#60]
当我 从签名服务器成功连通后，它会这样报错，我已升级到1.9.7
`Exception in resumeConnection.
2023-07-18T14:46:29.914994763Z java.lang.NoSuchMethodError: 'java.lang.String io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)'
2023-07-18T14:46:29.914999434Z 	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:123)
2023-07-18T14:46:29.915003155Z 	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
2023-07-18T14:46:29.915006589Z 	at org.asynchttpclient.netty.request.NettyRequestFactory.newNettyRequest(NettyRequestFactory.java:114)
2023-07-18T14:46:29.915010070Z 	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:204)
2023-07-18T14:46:29.915013633Z 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:136)
2023-07-18T14:46:29.915016877Z 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:114)
2023-07-18T14:46:29.915019967Z 	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
2023-07-18T14:46:29.915023155Z 	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:228)
2023-07-18T14:46:29.915026223Z 	at org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:39)
2023-07-18T14:46:29.915029287Z 	at xyz.cssxsh.mirai.tool.UnidbgFetchQsign.register(UnidbgFetchQsign.kt:69)
2023-07-18T14:46:29.915032312Z 	at xyz.cssxsh.mirai.tool.UnidbgFetchQsign.initialize(UnidbgFetchQsign.kt:52)
2023-07-18T14:46:29.915035466Z 	at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.kt:123)
2023-07-18T14:46:29.915038723Z 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
2023-07-18T14:46:29.915051498Z 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
2023-07-18T14:46:29.915054878Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-18T14:46:29.915058060Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
2023-07-18T14:46:29.915061230Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
2023-07-18T14:46:29.915064337Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
2023-07-18T14:46:29.915068207Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
2023-07-18T14:46:29.915071482Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-07-18T14:46:29.915074579Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
2023-07-18T14:46:29.915077714Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
2023-07-18T14:46:29.915080908Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
2023-07-18T14:46:29.915084097Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
2023-07-18T14:46:29.915087221Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-07-18T14:46:29.915090383Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
2023-07-18T14:46:29.915093495Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
2023-07-18T14:46:29.915096565Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
2023-07-18T14:46:29.915099724Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
2023-07-18T14:46:29.915102926Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-07-18T14:46:29.915106001Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
2023-07-18T14:46:29.915109116Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
2023-07-18T14:46:29.915112281Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
2023-07-18T14:46:29.915115371Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
2023-07-18T14:46:29.915118505Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-07-18T14:46:29.915125731Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
2023-07-18T14:46:29.915129268Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
2023-07-18T14:46:29.915144232Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
2023-07-18T14:46:29.915148457Z 	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
2023-07-18T14:46:29.915151601Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-07-18T14:46:29.915154678Z 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-18T14:46:29.915157738Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2023-07-18T14:46:29.915160818Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2023-07-18T14:46:29.915164086Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2023-07-18T14:46:29.915167282Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by cssxsh** [comment]
这个日志的排版不像是想让我看的样子

**Comment by cssxsh** [comment]
依赖版本问题，把你的 项目依赖配置贴一下

**Comment by ZZM-user** [comment]
> 依赖版本问题，把你的 项目依赖配置贴一下

![image](https://github.com/cssxsh/fix-protocol-version/assets/52201447/a5b25b36-f37f-4e3c-bf07-eaf49950dcdf)

**Comment by cssxsh** [comment]
https://search.maven.org/artifact/io.netty/netty-bom/4.1.94.Final/pom

用这个把 netty 版本统一一下

**Comment by ZZM-user** [comment]
> https://search.maven.org/artifact/io.netty/netty-bom/4.1.94.Final/pom
> 
> 用这个把 netty 版本统一一下

还是一样的错误
![image](https://github.com/cssxsh/fix-protocol-version/assets/52201447/e1c540b6-30fb-4df6-915b-c0d060d271f6)

**Comment by cssxsh** [comment]
你好像不会用 bom
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-bom</artifactId>
            <version>4.1.94.Final</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

另外 `mirai-login-solver-selenium` 是早就已经废弃的项目吧

**Comment by cssxsh** [comment]
> > 你好像不会用 bom
> > ```
> > <dependencyManagement>
> >     <dependencies>
> >         <dependency>
> >             <groupId>io.netty</groupId>
> >             <artifactId>netty-bom</artifactId>
> >             <version>4.1.94.Final</version>
> >             <type>pom</type>
> >             <scope>import</scope>
> >         </dependency>
> >     </dependencies>
> > </dependencyManagement>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外 `mirai-login-solver-selenium` 是早就已经废弃的项目吧
> 
> 好的，感谢你的耐心回复，至于mirai-login-solver-selenium，也是没有使用的东西了，只是还未移除

`mirai-login-solver-selenium` 的依赖里面就有 netty，这应该就是版本不一致的元凶
