### ISSUE TITLE
MsfOfflineToken

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [cssxsh/fix-protocol-version#64]
登陆成功然后MsfOfflineToken。
完整日志如下:
```
  18:11:59 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  18:11:59 [INFO] Runtime: OpenJDK 64-Bit Server VM 11.0.16 (arch: 64)
  18:11:59 [INFO] https://github.com/iTXTech/mirai-console-loader
  18:11:59 [INFO] This program is licensed under GNU AGPL v3
  18:12:01 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  18:12:01 [INFO] Verifying "net.mamoe:mirai-console" v2.15.0
  18:12:03 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.15.0
  18:12:03 [INFO] Verifying "net.mamoe:mirai-core-all" v2.15.0
  18:12:05 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.2
  18:12:05 [ERROR] "org.itxtech:mcl-addon" is corrupted.
  18:12:05 [INFO] Updating "org.itxtech:mcl-addon" to v2.1.2
  18:12:06 [ERROR] Cannot download package "org.itxtech:mcl-addon"
  18:12:06 [ERROR] The local file "org.itxtech:mcl-addon" is still corrupted, please check the network.
  18:12:06 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
2023-07-24 18:12:07 I/main: Starting mirai-console...
2023-07-24 18:12:07 I/main: 

===================================[ Mirai console 2.15.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-07-24 18:12:07 I/main: Backend: version 2.15.0, built on 2023-07-11 04:57:17.
2023-07-24 18:12:07 I/main: Frontend Terminal: version 2.15.0, provided by Mamoe Technologies
2023-07-24 18:12:07 I/main: Welcome to visit https://mirai.mamoe.net/
2023-07-24 18:12:09 I/fix-protocol-version: 协议版本检查更新...
2023-07-24 18:12:10 I/fix-protocol-version: ANDROID_PHONE load from file:///root/android_phone.json
2023-07-24 18:12:10 I/fix-protocol-version: 注册服务...
2023-07-24 18:12:10 I/fix-protocol-version: 服务配置文件 file:///root/KFCFactory.json
2023-07-24 18:12:10 I/plugin: Successfully loaded plugin fix-protocol-version v1.9.6
2023-07-24 18:12:10 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-07-24 18:12:10 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-07-24 18:12:10 I/fix-protocol-version: 当前各协议版本日期: 
ANDROID_PHONE  8.9.63.11390  2023-05-26T10:46:18+08:00
ANDROID_PAD    8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_WATCH  2.0.8         2019-06-03T20:25:31+08:00
IPAD           8.9.50.611    2023-02-16T15:10:14+08:00
MACOS          6.8.2.21241   2022-03-14T11:11:35+08:00

2023-07-24 18:12:11 I/Mirai HTTP API: ********************************************************
2023-07-24 18:12:11 I/MahKtorAdapter[http,ws]: Autoreload is disabled because the development mode is off.
2023-07-24 18:12:12 I/MahKtorAdapter[http,ws]: Application started in 0.374 seconds.
2023-07-24 18:12:12 I/MahKtorAdapter[http,ws]: Responding at http://0.0.0.0:0000
2023-07-24 18:12:12 I/http adapter: >>> [http adapter] is listening at http://0.0.0.0:0000
2023-07-24 18:12:12 I/ws adapter: >>> [ws adapter] is listening at ws://0.0.0.0:0000
2023-07-24 18:12:12 I/Mirai HTTP API: Http api server is running with verifyKey: **********
2023-07-24 18:12:12 I/Mirai HTTP API: adaptors: [http,ws]
2023-07-24 18:12:12 I/Mirai HTTP API: ********************************************************
2023-07-24 18:12:12 I/main: 2 plugin(s) enabled.
2023-07-24 18:12:12 I/main: Auto-login 1234567890, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-07-24 18:12:12 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///root/KFCFactory.json)
2023-07-24 18:12:12 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-07-24 18:12:12 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-07-24 18:12:12 W/EncryptService.alert: Service details:
2023-07-24 18:12:12 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-07-24 18:12:12 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.9.6.mirai2.jar}
2023-07-24 18:12:12 W/EncryptService.alert:   `- Source: file:/root/plugins/fix-protocol-version-1.9.6.mirai2.jar
2023-07-24 18:12:12 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/root/plugins/fix-protocol-version-1.9.6.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.9.6.mirai2.jar}
 <no principals>
 java.security.Permissions@1573e8a5 (
 ("java.io.FilePermission" "/root/plugins/fix-protocol-version-1.9.6.mirai2.jar" "read")
)


2023-07-24 18:12:12 I/TLV544Provider: unidbg-fetch-qsign by https://******** about 
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.5",
        "protocol": {
            "qua": "*****",
            "version": "8.9.63",
            "code": "*****"
        }
    }
}
2023-07-24 18:12:13 I/Bot.1234567890: Loaded account secrets from local cache.
2023-07-24 18:12:13 I/UnidbgFetchQsign: Bot(1234567890) initialize by https://*********
2023-07-24 18:12:25 I/UnidbgFetchQsign: Bot(1234567890) register, Instance loaded successfully.
2023-07-24 18:12:25 I/UnidbgFetchQsign: Bot(1234567890) initialize complete
2023-07-24 18:12:28 I/Bot.1234567890: Saved account secrets to local cache for fast login.
2023-07-24 18:12:28 I/Bot.1234567890: Login successful.
2023-07-24 18:12:28 I/Bot.1234567890: Bot login successful.
2023-07-24 18:12:28 V/Bot.1234567890: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Success@3cb04dd
2023-07-24 18:12:28 I/main: mirai-console started successfully.
2023-07-24 18:12:29 W/UnidbgFetchQsign: with CoroutineName(SendMessage)
MsfOfflineToken(uin=1234567890, seq=**********, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:299)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: StateSwitchingException(old=StateLoading, new=StateClosed, cause=MsfOfflineToken(uin=1234567890, seq==**********,, const=0))
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:425)
		at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:108)
		at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:326)
		at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:281)
		at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
		at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
		at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:161)
		... 21 more
	Caused by: [CIRCULAR REFERENCE: MsfOfflineToken(uin=1234567890, seq==**********,, const=0)]

2023-07-24 18:12:29 I/Bot.1234567890: Bot cancelled: Bot closed
```

**Comment by cssxsh** [comment]
MsfOfflineToken 是服务器主动将用户踢下线

**Comment by Asanatsa** [comment]
> MsfOfflineToken 是服务器主动将用户踢下线

请问一下什么条件会触发自动下线，我这边也遇到了相同的问题
