### ISSUE TITLE
加载提示java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by smilecat2788** [cssxsh/fix-protocol-version#71]
2023-08-06 16:38:16 I/main: 14 plugin(s) enabled.
2023-08-06 16:38:16 I/main: Auto-login 483392198, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-08-06 16:38:16 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///home/mira/KFCFactory.json)
2023-08-06 16:38:16 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-08-06 16:38:16 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-08-06 16:38:16 W/EncryptService.alert: Service details:
2023-08-06 16:38:16 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-08-06 16:38:16 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.9.11.mirai2.jar}
2023-08-06 16:38:16 W/EncryptService.alert:   `- Source: file:/home/mira/plugins/fix-protocol-version-1.9.11.mirai2.jar
2023-08-06 16:38:16 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/home/mira/plugins/fix-protocol-version-1.9.11.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.9.11.mirai2.jar}
 <no principals>
 java.security.Permissions@5c70c771 (
 ("java.io.FilePermission" "/home/mira/plugins/fix-protocol-version-1.9.11.mirai2.jar" "read")
)

2023-08-06 16:38:17 I/KFCFactory: ANDROID_PHONE(8.9.58) server type: kiliokuara/magic-signer-guide, file:///home/mira/KFCFactory.json
2023-08-06 16:38:17 I/KFCFactory: magic-signer-guide by http://127.0.0.1:8888 about 
{"main_page":"https://github.com/kiliokuara/magic-signer-guide/issues","server_version":"70107d8e1b4acb747026c95a853523b575e7d98f","server_build_time":1690883369515,"supported_protocol_versions":["8.9.58"]}
2023-08-06 16:38:17 I/BiliBili Dynamic: BiliBili UID: 1654626471
2023-08-06 16:38:18 I/BiliBili Dynamic: 加载字体 LXGW WenKai 成功
2023-08-06 16:38:25 I/ViVo50: Bot(483392198) initialize by http://127.0.0.1:8888
2023-08-06 16:38:26 I/ViVo50: Session(bot=483392198) opened
2023-08-06 16:38:26 E/main: java.lang.IllegalStateException: Session(bot=483392198) rpc.initialize error: "java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space"
java.lang.IllegalStateException: Session(bot=483392198) rpc.initialize error: "java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space"
        at fix-protocol-version-1.9.11.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50$Session.sendCommand(ViVo50.kt:434)
        at fix-protocol-version-1.9.11.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50.initialize(ViVo50.kt:106)
        at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.kt:123)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-08-06 16:38:26 I/Bot.483392198: Bot cancelled: Bot closed
2023-08-06 16:38:26 V/Bot.483392198: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@6792f2c6
2023-08-06 16:38:26 I/main: mirai-console started successfully.
2023-08-06 16:38:28 I/SteamHelper: 信息刷新线程执行完毕
>

**Comment by smilecat2788** [comment]
呃，把签名服务的docker内存限制从200MB改成300MB好像就好了，但是容器内存占用仍然99.97%
