### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by J-EnJay** [cssxsh/fix-protocol-version#76]
### io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080
不清楚这个ip从何而来，但是连接超时

```
2023-09-12 02:27:15 I/KFCFactory: ANDROID_PHONE(8.9.63) EncryptService by fuqiuluo/unidbg-fetch-qsign from file:///D:/Program%20Files%20Protable/MCL3/KFCFactory.json
2023-09-12 02:27:15 I/KFCFactory: unidbg-fetch-qsign by http://127.0.0.1:8800 about
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.9",
        "protocol": {
            "qua": "V1_AND_SQ_8.9.63_4194_YYB_D",
            "version": "8.9.63",
            "code": "4194",
            "package_name": "com.tencent.mobileqq"
        }
    }
}
2023-09-12 02:27:16 I/UnidbgFetchQsign: Bot(2140821596) initialize by http://127.0.0.1:8800
2023-09-12 02:27:19 I/UnidbgFetchQsign: Bot(2140821596) register, Instance loaded successfully.
2023-09-12 02:27:19 I/UnidbgFetchQsign: Bot(2140821596) initialize complete
2023-09-12 02:27:41 W/UnidbgFetchQsign: with CoroutineName(SendMessage)
java.lang.RuntimeException: Bot(2140821596) callback trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
        at fix-protocol-version-1.11.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$callback$1.invokeSuspend(UnidbgFetchQsign.kt:236)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: NettyChannelException(message=Failed to connect 36.155.163.51/<unresolved>:8080, cause=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$suspendImpl(NettyNetworkHandler.kt:116)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$createConnection$1.invokeSuspend(NettyNetworkHandler.kt)
        ... 6 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080
Caused by: java.net.ConnectException: Connection timed out: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-09-12 02:27:41 E/main: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080
        Suppressed: NettyChannelException(message=Failed to connect 36.155.163.51/<unresolved>:8080, cause=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$suspendImpl(NettyNetworkHandler.kt:116)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$createConnection$1.invokeSuspend(NettyNetworkHandler.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Caused by: [CIRCULAR REFERENCE: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /36.155.163.51:8080]
Caused by: java.net.ConnectException: Connection timed out: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-09-12 02:27:41 I/UnidbgFetchQsign: Bot(2140821596) destroy, Instance destroyed successfully.
2023-09-12 02:27:41 V/Bot.2140821596: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@3dd4f91d
2023-09-12 02:27:41 I/main: mirai-console started successfully.
2023-09-12 02:27:41 I/Bot.2140821596: Bot cancelled: Bot closed

```

**Comment by cssxsh** [comment]
连不上tx的服务器

另外，你应该 BUG 的格式提交
