### ISSUE TITLE
已经配置签名服务但仍然出现 code=45 错误，希望更新一下对 8.9.73 版本协议的支持

### ISSUE THREAD

**Issue by lcx1969001** [cssxsh/fix-protocol-version#85]
### 问题描述

已经配置签名服务 unidbg-fetch-qsign:1.1.7 使用的是 8.9.63 版本协议，但部分账号登录时仍出现 code=45 错误，目前 unidbg-fetch-qsign 最新的已经支持 8.9.73 版本协议，希望更新一下对 8.9.73 版本协议的支持

### 复现

我有四个账号，其中两个已注册超过一年，其中一个是最近三个月内注册的，还有一个是刚刚用最新版手机QQ注册的。
现在四个账号均使用  unidbg-fetch-qsign:1.1.7 签名服务 ANDROID_PAD 8.9.63 协议登录
登录结果：两个已注册超过一年的账号可以正常登录，最近三个月内注册的和刚刚注册的账号登录时出现 code=45 错误

### mirai-core 版本

2.16.0-RC

### bot-protocol

ANDROID_PAD

### 签名服务

unidbg-fetch-qsign:1.1.7

### 系统日志

```plain text
2023-10-09 19:21:04 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///C:/home/project/java/mirai/mirai-air/KFCFactory.json)
        2023-10-09 19:21:04 W/EncryptService.alert: All outgoing message may be leaked by this service.
        2023-10-09 19:21:04 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
        2023-10-09 19:21:04 W/EncryptService.alert: Service details:
        2023-10-09 19:21:04 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
        2023-10-09 19:21:04 W/EncryptService.alert:   `- ClassLoader: sun.misc.Launcher$AppClassLoader@18b4aac2
        2023-10-09 19:21:04 W/EncryptService.alert:   `- Source: file:/C:/Users/Administrator/.m2/repository/net/mamoe/fix-protocol-version/1.10.0/fix-protocol-version-1.10.0.jar
        2023-10-09 19:21:04 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/C:/Users/Administrator/.m2/repository/net/mamoe/fix-protocol-version/1.10.0/fix-protocol-version-1.10.0.jar <no signer certificates>)
        sun.misc.Launcher$AppClassLoader@18b4aac2
<no principals>
 java.security.Permissions@4d964c9e (
        ("java.util.PropertyPermission" "java.specification.version" "read")
        ("java.util.PropertyPermission" "java.version" "read")
        ("java.util.PropertyPermission" "os.arch" "read")
        ("java.util.PropertyPermission" "java.specification.vendor" "read")
        ("java.util.PropertyPermission" "java.vm.specification.name" "read")
        ("java.util.PropertyPermission" "java.vm.vendor" "read")
        ("java.util.PropertyPermission" "path.separator" "read")
        ("java.util.PropertyPermission" "os.version" "read")
        ("java.util.PropertyPermission" "file.separator" "read")
        ("java.util.PropertyPermission" "line.separator" "read")
        ("java.util.PropertyPermission" "java.vm.specification.vendor" "read")
        ("java.util.PropertyPermission" "java.specification.name" "read")
        ("java.util.PropertyPermission" "java.vendor.url" "read")
        ("java.util.PropertyPermission" "java.vendor" "read")
        ("java.util.PropertyPermission" "java.vm.version" "read")
        ("java.util.PropertyPermission" "java.vm.name" "read")
        ("java.util.PropertyPermission" "java.vm.specification.version" "read")
        ("java.util.PropertyPermission" "os.name" "read")
        ("java.util.PropertyPermission" "java.class.version" "read")
        ("java.lang.RuntimePermission" "exitVM")
        ("java.lang.RuntimePermission" "stopThread")
        ("java.io.FilePermission" "\C:\Users\Administrator\.m2\repository\net\mamoe\fix-protocol-version\1.10.0\fix-protocol-version-1.10.0.jar" "read")
        ("java.net.SocketPermission" "localhost:0" "listen,resolve")
        )


        2023-10-09 19:21:04 I/KFCFactory: ANDROID_PAD(8.9.63) EncryptService by fuqiuluo/unidbg-fetch-qsign from file:///C:/home/project/java/mirai/mirai-air/KFCFactory.json
        2023-10-09 19:21:04 I/KFCFactory: unidbg-fetch-qsign by http://dev.ckem.top:8192 about
        {
        "code": 0,
        "msg": "IAA 云天明 章北海",
        "data": {
        "version": "1.1.7",
        "protocol": {
        "qua": "V1_AND_SQ_8.9.63_4194_YYB_D",
        "version": "8.9.63",
        "code": "4194"
        }
        }
        }
        2023-10-09 19:21:05 I/UnidbgFetchQsign: Bot(2478298072) initialize by http://dev.ckem.top:8192
        2023-10-09 19:21:08 I/UnidbgFetchQsign: Bot(2478298072) register, Instance loaded successfully.
        2023-10-09 19:21:08 I/UnidbgFetchQsign: Bot(2478298072) initialize complete
        2023-10-09 19:21:08.865 INFO  [atcher-worker-5] c.q.s.component.mirai.MiraiBotLogger    : ECDH 密钥无效, 开始从服务器获取 ecdh 公钥
        2023-10-09 19:21:09.164 INFO  [atcher-worker-3] c.q.s.component.mirai.MiraiBotLogger    : 成功从服务器获取 ecdh 公钥
        2023-10-09 19:21:09 D/UnidbgFetchQsign: Bot(2478298072) custom_energy 810_9, success
        2023-10-09 19:21:09 D/UnidbgFetchQsign: Bot(2478298072) sign wtlogin.login, success
        2023-10-09 19:21:09 D/UnidbgFetchQsign: Bot(2478298072) sendMessage trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
        2023-10-09 19:21:10.114 INFO  [ntLoopGroup-4-3] c.q.s.component.mirai.MiraiBotLogger    : Calculating type 2 PoW, it can take some time....
        2023-10-09 19:21:10 D/UnidbgFetchQsign: Bot(2478298072) sign trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, success
        2023-10-09 19:21:10.191 INFO  [ntLoopGroup-4-3] c.q.s.component.mirai.MiraiBotLogger    : Got PoW result, cost: 77 ms
        2023-10-09 19:21:11 D/UnidbgFetchQsign: Bot(2478298072) submit trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, submit success
        2023-10-09 19:21:11 D/UnidbgFetchQsign: Bot(2478298072) sendMessage trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
        2023-10-09 19:21:11 D/UnidbgFetchQsign: Bot(2478298072) sign trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, success
        2023-10-09 19:21:11 D/UnidbgFetchQsign: Bot(2478298072) submit trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, submit success
        2023-10-09 19:21:41 D/UnidbgFetchQsign: Bot(2478298072) custom_energy 810_2, success
        2023-10-09 19:21:41 D/UnidbgFetchQsign: Bot(2478298072) sign wtlogin.login, success
        2023-10-09 19:21:41.683 WARN  [atcher-worker-3] c.q.s.component.mirai.MiraiBotLogger    : Failed with auth method: Password@80809447
        net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        2023-10-09 19:21:41.686 WARN  [atcher-worker-3] c.q.s.component.mirai.MiraiBotLogger    : Exception in resumeConnection.
        net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException: null
        2023-10-09 19:21:41.735 INFO  [atcher-worker-4] c.q.s.component.mirai.MiraiBotLogger    : ECDH 密钥有效
        2023-10-09 19:21:41.740 WARN  [atcher-worker-4] c.q.s.component.mirai.MiraiBotLogger    : Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]@875687974
        net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        ... 5 common frames omitted
        2023-10-09 19:21:41.742 WARN  [atcher-worker-4] c.q.s.component.mirai.MiraiBotLogger    : Exception in resumeConnection.
        net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        ... 6 common frames omitted
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        ... 5 common frames omitted
        2023-10-09 19:21:41.742 WARN  [atcher-worker-4] c.q.s.component.mirai.MiraiBotLogger    : Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)
        2023-10-09 19:21:41 I/UnidbgFetchQsign: Bot(2478298072) destroy, Instance destroyed successfully.
        2023-10-09 19:21:41.798 INFO  [ntLoopGroup-4-6] c.q.s.component.mirai.MiraiBotLogger    : Bot cancelled: Bot closed
        2023-10-09 19:21:41.825 ERROR [           main] o.springframework.boot.SpringApplication: Application run failed
        net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2478298072), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        ... 5 common frames omitted
        2023-10-09 19:21:41.828 INFO  [           main] o.s.c.n.e.s.EurekaServiceRegistry       : Unregistering application BOT-AIR with eureka with status DOWN
        2023-10-09 19:21:41.828 INFO  [           main] com.netflix.discovery.DiscoveryClient   : Saw local status change event StatusChangeEvent [timestamp=1696850501828, current=DOWN, previous=UP]
        2023-10-09 19:21:41.828 INFO  [nfoReplicator-0] com.netflix.discovery.DiscoveryClient   : DiscoveryClient_BOT-AIR/host.docker.internal:bot-air:18120: registering service...
        2023-10-09 19:21:41.886 INFO  [nfoReplicator-0] com.netflix.discovery.DiscoveryClient   : DiscoveryClient_BOT-AIR/host.docker.internal:bot-air:18120 - registration status: 204
        2023-10-09 19:21:41.895 INFO  [tureContainer-2] o.s.a.r.l.SimpleMessageListenerContainer: Waiting for workers to finish.
        2023-10-09 19:21:42.619 INFO  [tureContainer-2] o.s.a.r.l.SimpleMessageListenerContainer: Successfully waited for workers to finish.
        2023-10-09 19:21:42.817 INFO  [           main] o.apache.coyote.http11.Http11NioProtocol: Pausing ProtocolHandler ["http-nio-18120"]
        2023-10-09 19:21:42.817 INFO  [           main] org.apache.catalina.core.StandardService: Stopping service [Tomcat]
        2023-10-09 19:21:42.821 INFO  [           main] o.apache.coyote.http11.Http11NioProtocol: Stopping ProtocolHandler ["http-nio-18120"]
        2023-10-09 19:21:42.824 INFO  [           main] o.apache.coyote.http11.Http11NioProtocol: Destroying ProtocolHandler ["http-nio-18120"]
        2023-10-09 19:21:42.832 INFO  [           main] o.s.a.r.l.SimpleMessageListenerContainer: Shutdown ignored - container is already stopped
        2023-10-09 19:21:42.890 INFO  [           main] com.netflix.discovery.DiscoveryClient   : Shutting down DiscoveryClient ...
        2023-10-09 19:21:45.893 INFO  [           main] com.netflix.discovery.DiscoveryClient   : Unregistering ...
        2023-10-09 19:21:45.956 INFO  [           main] com.netflix.discovery.DiscoveryClient   : DiscoveryClient_BOT-AIR/host.docker.internal:bot-air:18120 - deregister  status: 200
        2023-10-09 19:21:45.959 INFO  [           main] com.netflix.discovery.DiscoveryClient   : Completed shut down of DiscoveryClient
```

**Comment by xszqxszq** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki#go-cqhttp

第一个保存为android_pad.json，第二个保存为android_phone.json，丢bot根目录下，重启应该就自动加载上了，或者cli输入protocol load ANDROID_PHONE之类的手动加载

**Comment by lcx1969001** [comment]
> https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki#go-cqhttp
> 
> 第一个保存为android_pad.json，第二个保存为android_phone.json，丢bot根目录下，重启应该就自动加载上了，或者cli输入protocol load ANDROID_PHONE之类的手动加载

成功登录了，非常感谢
