### ISSUE TITLE
对接Shamrock ProAPI时出现如下报错

### ISSUE THREAD

**Issue by ShiaBox** [cssxsh/fix-protocol-version#91]
### 问题描述

正常接入Shamrock，看日志中插件已获取到shamrock返回的协议信息，但无法正常使用。
最终报错如下：
```
2023-11-29 17:43:18 E/main: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instea
d at path: $
JSON input:
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input:
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:582)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:223)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:206)
        at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:76)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:97)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:97)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.Shamrock.services(Shamrock.kt:67)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.Shamrock.initialize(Shamrock.kt:52)
        at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.k
t:123)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 复现

在配置文件中配置shamrock的proapi
```
{
    "8.9.83": {
        "base_url": "http://xxxx:8983",
        "type": "Shamrock",
        "key": "114514"
    }
}
```

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PAD

### 签名服务

shamrock1.0.5dev

### 系统日志

```plain text
2023-11-29 17:39:58 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///C:/shiaworkshop/mcsmanager/daemon/data/InstanceData/Dice-2023-03-10/KFCFactory.json)
2023-11-29 17:39:58 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-11-29 17:39:58 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-11-29 17:39:58 W/EncryptService.alert: Service details:
2023-11-29 17:39:58 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-11-29 17:39:58 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.13.0.mirai2.jar}
2023-11-29 17:39:58 W/EncryptService.alert:   `- Source: file:/C:/shiaworkshop/mcsmanager/daemon/data/InstanceData/Dice-2023-03-10/plugins/fix-protocol-version-1.13.0.mirai2.jar
2023-11-29 17:39:58 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/C:/shiaworkshop/mcsmanager/daemon/data/InstanceData/Dice-2023-03-10/plugins/fix-protocol-version-1.13.0.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.13.0.mirai2.jar}
 <no principals>
 java.security.Permissions@daf8f9 (
 ("java.io.FilePermission" "C:\shiaworkshop\mcsmanager\daemon\data\InstanceData\Dice-2023-03-10\plugins\fix-protocol-version-1.13.0.mirai2.jar" "read")
)


2023-11-29 17:39:59 I/KFCFactory: create EncryptService(id=215****87), protocol=ANDROID_PAD(8.9.83) by Shamrock from file:///C:/shiaworkshop/mcsmanager/daemon/data/InstanceData/Dice-2023-03-10/KFCFactory.json
2023-11-29 17:39:59 I/KFCFactory: Shamrock by http://****:8983 about 
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "processName": "com.tencent.mobileqq",
        "subAppId": 537178685,
        "qua": "V1_AND_SQ_8.9.83_4680_YYB_D",
        "ntVersion": 100,
        "msfConnNetType": 0,
        "qimei": "",
        "svnVersion": "[2554]",
        "androidId": "86bb1****7a114",
        "guid": "1e0d4a****39490",
        "ksid": "284e9****aabf531",
        "netType": 2,
        "pingVersion": 1,
        "ssoVer": 1536,
        "ssoVersion": 20,
        "dbVersion": 1,
        "SSOVer": 20,
        "tgtgtVer": 4,
        "androidDevInfo": "0a0575626f6f741282014c696e75782076657273696f6e20342e31392e37312b2028636a77406d762d646576312920286763632076657273696f6e20342e392e78203****462612d343831372d386135332d6633613465633037353231613a103662616130346239333438353838613442004a1772656c2e636a772e32303232303531382e313134313333",
        "signDtConfig": {
            "en": [
                [
                    3,
                    5,
                    7,
                    6,
                    4,
                    8,
                    1,
                    12,
                    10,
                    15,
                    9,
                    11,
                    13,
                    0,
                    2,
                    14
                ],
                [
                    15,
                    13,
                    1,
                    11,
                    4,
                    2,
                    5,
                    8,
                    14,
                    6,
                    0,
                    7,
                    10,
                    12,
                    3,
                    9
                ],
                [
                    11,
                    5,
                    0,
                    1,
                    4,
                    3,
                    2,
                    6,
                    10,
                    14,
                    12,
                    8,
                    9,
                    7,
                    13,
                    15
                ],
                [
                    7,
                    14,
                    6,
                    13,
                    11,
                    1,
                    10,
                    12,
                    2,
                    0,
                    9,
                    3,
                    8,
                    4,
                    5,
                    15
                ],
                [
                    3,
                    6,
                    0,
                    9,
                    14,
                    15,
                    12,
                    8,
                    5,
                    1,
                    7,
                    4,
                    11,
                    10,
                    2,
                    13
                ],
                [
                    15,
                    14,
                    11,
                    12,
                    2,
                    8,
                    6,
                    5,
                    3,
                    10,
                    13,
                    9,
                    4,
                    7,
                    0,
                    1
                ],
                [
                    11,
                    7,
                    5,
                    3,
                    4,
                    0,
                    12,
                    15,
                    1,
                    14,
                    13,
                    10,
                    8,
                    6,
                    9,
                    2
                ],
                [
                    7,
                    15,
                    1,
                    11,
                    3,
                    4,
                    13,
                    9,
                    8,
                    6,
                    0,
                    12,
                    5,
                    14,
                    10,
                    2
                ],
                [
                    3,
                    7,
                    10,
                    0,
                    13,
                    1,
                    5,
                    2,
                    14,
                    9,
                    12,
                    11,
                    6,
                    4,
                    8,
                    15
                ],
                [
                    15,
                    3,
                    9,
                    10,
                    1,
                    13,
                    5,
                    7,
                    6,
                    8,
                    4,
                    0,
                    11,
                    14,
                    12,
                    2
                ],
                [
                    11,
                    8,
                    15,
                    6,
                    1,
                    5,
                    12,
                    3,
                    2,
                    14,
                    7,
                    13,
                    4,
                    0,
                    10,
                    9
                ],
                [
                    7,
                    8,
                    1,
                    9,
                    2,
                    0,
                    3,
                    11,
                    5,
                    15,
                    13,
                    4,
                    14,
                    6,
                    10,
                    12
                ],
                [
                    4,
                    7,
                    13,
                    3,
                    2,
                    14,
                    10,
                    9,
                    5,
                    12,
                    6,
                    0,
                    15,
                    1,
                    11,
                    8
                ],
                [
                    0,
                    15,
                    7,
                    10,
                    8,
                    11,
                    3,
                    4,
                    9,
                    5,
                    2,
                    1,
                    14,
                    6,
                    12,
                    13
                ],
                [
                    12,
                    7,
                    2,
                    15,
                    1,
                    10,
                    3,
                    4,
                    6,
                    9,
                    0,
                    8,
                    5,
                    14,
                    11,
                    13
                ],
                [
                    8,
                    11,
                    9,
                    7,
                    15,
                    6,
                    1,
                    12,
                    14,
                    3,
                    13,
                    4,
                    0,
                    10,
                    2,
                    5
                ],
                [
                    4,
                    8,
                    7,
                    15,
                    5,
                    10,
                    14,
                    6,
                    12,
                    13,
                    11,
                    2,
                    9,
                    3,
                    0,
                    1
                ],
                [
                    0,
                    7,
                    6,
                    12,
                    11,
                    15,
                    4,
                    2,
                    10,
                    14,
                    13,
                    1,
                    8,
                    9,
                    5,
                    3
                ],
                [
                    12,
                    9,
                    11,
                    15,
                    10,
                    5,
                    8,
                    7,
                    6,
                    13,
                    1,
                    3,
                    2,
                    4,
                    14,
                    0
                ],
                [
                    8,
                    1,
                    6,
                    0,
                    7,
                    4,
                    9,
                    12,
                    15,
                    5,
                    14,
                    13,
                    10,
                    11,
                    3,
                    2
                ],
                [
                    4,
                    9,
                    14,
                    2,
                    13,
                    15,
                    5,
                    12,
                    8,
                    10,
                    0,
                    3,
                    6,
                    11,
                    1,
                    7
                ],
                [
                    0,
                    2,
                    11,
                    7,
                    3,
                    6,
                    15,
                    12,
                    1,
                    9,
                    8,
                    4,
                    5,
                    13,
                    14,
                    10
                ],
                [
                    12,
                    10,
                    5,
                    15,
                    3,
                    14,
                    11,
                    13,
                    2,
                    9,
                    0,
                    1,
                    7,
                    6,
                    8,
                    4
                ],
                [
                    8,
                    2,
                    15,
                    6,
                    7,
                    10,
                    9,
                    14,
                    4,
                    3,
                    13,
                    5,
                    1,
                    12,
                    11,
                    0
                ],
                [
                    4,
                    11,
                    10,
                    14,
                    15,
                    7,
                    8,
                    6,
                    5,
                    0,
                    12,
                    13,
                    3,
                    1,
                    9,
                    2
                ],
                [
                    0,
                    3,
                    4,
                    5,
                    7,
                    13,
                    1,
                    12,
                    15,
                    6,
                    10,
                    14,
                    9,
                    11,
                    8,
                    2
                ],
                [
                    13,
                    9,
                    8,
                    15,
                    0,
                    4,
                    1,
                    14,
                    12,
                    6,
                    5,
                    7,
                    3,
                    10,
                    2,
                    11
                ],
                [
                    9,
                    2,
                    1,
                    6,
                    4,
                    10,
                    8,
                    11,
                    7,
                    13,
                    3,
                    12,
                    14,
                    15,
                    5,
                    0
                ],
                [
                    5,
                    10,
                    13,
                    14,
                    12,
                    7,
                    3,
                    8,
                    1,
                    0,
                    15,
                    9,
                    4,
                    11,
                    6,
                    2
                ],
                [
                    1,
                    2,
                    7,
                    6,
                    4,
                    9,
                    0,
                    12,
                    14,
                    15,
                    8,
                    13,
                    10,
                    3,
                    11,
                    5
                ],
                [
                    13,
                    11,
                    2,
                    0,
                    12,
                    9,
                    6,
                    8,
                    4,
                    3,
                    14,
                    7,
                    1,
                    10,
                    5,
                    15
                ],
                [
                    9,
                    3,
                    12,
                    5,
                    4,
                    13,
                    14,
                    0,
                    10,
                    2,
                    7,
                    15,
                    8,
                    6,
                    1,
                    11
                ]
            ],
            "de": [
                [
                    12,
                    8,
                    0,
                    15,
                    3,
                    14,
                    4,
                    1,
                    13,
                    6,
                    9,
                    5,
                    11,
                    2,
                    10,
                    7
                ],
                [
                    4,
                    6,
                    5,
                    7,
                    9,
                    13,
                    15,
                    8,
                    2,
                    10,
                    11,
                    3,
                    14,
                    12,
                    0,
                    1
                ],
                [
                    9,
                    12,
                    2,
                    3,
                    7,
                    5,
                    4,
                    1,
                    15,
                    13,
                    0,
                    14,
                    8,
                    11,
                    10,
                    6
                ],
                [
                    15,
                    8,
                    5,
                    10,
                    7,
                    11,
                    0,
                    9,
                    6,
                    4,
                    2,
                    1,
                    3,
                    14,
                    13,
                    12
                ],
                [
                    7,
                    6,
                    0,
                    15,
                    3,
                    10,
                    9,
                    2,
                    1,
                    5,
                    8,
                    13,
                    11,
                    4,
                    14,
                    12
                ],
                [
                    8,
                    15,
                    12,
                    9,
                    13,
                    6,
                    4,
                    11,
                    1,
                    3,
                    10,
                    2,
                    14,
                    7,
                    0,
                    5
                ],
                [
                    8,
                    14,
                    13,
                    10,
                    3,
                    12,
                    6,
                    4,
                    11,
                    1,
                    0,
                    15,
                    2,
                    5,
                    9,
                    7
                ],
                [
                    2,
                    1,
                    14,
                    13,
                    15,
                    5,
                    0,
                    8,
                    11,
                    3,
                    12,
                    6,
                    9,
                    4,
                    7,
                    10
                ],
                [
                    14,
                    10,
                    0,
                    13,
                    3,
                    9,
                    15,
                    12,
                    4,
                    1,
                    7,
                    5,
                    6,
                    11,
                    8,
                    2
                ],
                [
                    5,
                    9,
                    1,
                    14,
                    8,
                    13,
                    6,
                    12,
                    3,
                    11,
                    7,
                    2,
                    15,
                    4,
                    0,
                    10
                ],
                [
                    1,
                    4,
                    5,
                    10,
                    3,
                    2,
                    8,
                    7,
                    9,
                    13,
                    0,
                    15,
                    6,
                    14,
                    12,
                    11
                ],
                [
                    2,
                    14,
                    1,
                    5,
                    7,
                    13,
                    0,
                    4,
                    12,
                    6,
                    11,
                    3,
                    8,
                    15,
                    10,
                    9
                ],
                [
                    15,
                    14,
                    0,
                    12,
                    4,
                    10,
                    5,
                    11,
                    6,
                    7,
                    2,
                    1,
                    9,
                    8,
                    13,
                    3
                ],
                [
                    7,
                    15,
                    13,
                    1,
                    2,
                    11,
                    3,
                    5,
                    9,
                    8,
                    10,
                    12,
                    4,
                    6,
                    0,
                    14
                ],
                [
                    12,
                    7,
                    15,
                    5,
                    4,
                    6,
                    9,
                    10,
                    8,
                    13,
                    0,
                    1,
                    11,
                    14,
                    3,
                    2
                ],
                [
                    3,
                    5,
                    1,
                    2,
                    7,
                    10,
                    15,
                    0,
                    11,
                    9,
                    4,
                    14,
                    12,
                    8,
                    6,
                    13
                ],
                [
                    5,
                    8,
                    14,
                    0,
                    10,
                    11,
                    15,
                    4,
                    9,
                    13,
                    1,
                    12,
                    6,
                    2,
                    7,
                    3
                ],
                [
                    7,
                    12,
                    1,
                    14,
                    6,
                    15,
                    13,
                    3,
                    2,
                    10,
                    4,
                    9,
                    11,
                    8,
                    5,
                    0
                ],
                [
                    11,
                    7,
                    6,
                    9,
                    4,
                    5,
                    13,
                    12,
                    8,
                    2,
                    0,
                    10,
                    3,
                    1,
                    14,
                    15
                ],
                [
                    9,
                    8,
                    14,
                    1,
                    7,
                    6,
                    3,
                    0,
                    11,
                    4,
                    10,
                    5,
                    2,
                    15,
                    12,
                    13
                ],
                [
                    9,
                    6,
                    12,
                    0,
                    7,
                    11,
                    4,
                    2,
                    10,
                    5,
                    14,
                    1,
                    13,
                    3,
                    15,
                    8
                ],
                [
                    5,
                    2,
                    6,
                    9,
                    1,
                    4,
                    7,
                    11,
                    3,
                    13,
                    12,
                    8,
                    15,
                    10,
                    14,
                    0
                ],
                [
                    4,
                    2,
                    3,
                    7,
                    14,
                    5,
                    12,
                    11,
                    9,
                    8,
                    15,
                    0,
                    1,
                    13,
                    6,
                    10
                ],
                [
                    14,
                    3,
                    11,
                    13,
                    1,
                    7,
                    2,
                    0,
                    10,
                    4,
                    9,
                    6,
                    12,
                    15,
                    5,
                    8
                ],
                [
                    13,
                    10,
                    7,
                    0,
                    12,
                    14,
                    15,
                    4,
                    3,
                    5,
                    11,
                    2,
                    6,
                    1,
                    8,
                    9
                ],
                [
                    6,
                    7,
                    12,
                    3,
                    8,
                    1,
                    11,
                    5,
                    14,
                    4,
                    15,
                    2,
                    10,
                    13,
                    9,
                    0
                ],
                [
                    7,
                    15,
                    4,
                    10,
                    12,
                    6,
                    8,
                    13,
                    14,
                    5,
                    9,
                    1,
                    0,
                    3,
                    11,
                    2
                ],
                [
                    13,
                    2,
                    8,
                    7,
                    10,
                    6,
                    1,
                    0,
                    5,
                    4,
                    15,
                    9,
                    11,
                    14,
                    12,
                    3
                ],
                [
                    6,
                    3,
                    7,
                    2,
                    0,
                    8,
                    11,
                    15,
                    13,
                    10,
                    5,
                    12,
                    1,
                    9,
                    4,
                    14
                ],
                [
                    0,
                    3,
                    12,
                    6,
                    1,
                    8,
                    4,
                    5,
                    9,
                    7,
                    14,
                    15,
                    11,
                    13,
                    2,
                    10
                ],
                [
                    8,
                    11,
                    9,
                    5,
                    12,
                    15,
                    14,
                    7,
                    2,
                    6,
                    10,
                    3,
                    0,
                    1,
                    4,
                    13
                ],
                [
                    11,
                    8,
                    3,
                    2,
                    15,
                    1,
                    4,
                    6,
                    0,
                    7,
                    9,
                    10,
                    14,
                    12,
                    5,
                    13
                ]
            ]
        }
    }
}
2023-11-29 17:40:00 I/Shamrock: Bot(21****87) initialize by http://****.cn:8983
2023-11-29 17:40:01 E/main: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input: 
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input: 
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:582)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:223)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:206)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:76)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:97)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:97)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.Shamrock.services(Shamrock.kt:67)
	at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.Shamrock.initialize(Shamrock.kt:52)
	at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.kt:123)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-11-29 17:40:01 I/Bot.215****87: Bot cancelled: Bot closed
2023-11-29 17:40:01 V/Bot.215****87: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@e75786
2023-11-29 17:40:01 I/main: mirai-console started successfully.
```

**Comment by cssxsh** [comment]
如果你是用的 OpenShamrock

https://github.com/whitechi73/OpenShamrock/blob/39120bdeaec2efe69905175f1cf966f5a4e1d268/xposed/src/main/java/moe/fuqiuluo/shamrock/remote/HTTPServer.kt#L67-L70

**Comment by ShiaBox** [comment]
并不是openshamrock，是之前的shamrock

**Comment by ShiaBox** [comment]
更换openshamrock登录和mirai相同账号后日志如下
```
2023-12-01 16:09:25 E/main: java.lang.IllegalStateException: No Match 215****087
java.lang.IllegalStateException: No Match 215****087
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.Shamrock.initialize(Shamrock.kt:52)
        at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.initializeSsoSecureEcdh(EcdhInitialPublicKeyUpdater.k
t:123)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:224)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-12-01 16:09:25 I/Bot.215****087: Bot cancelled: Bot closed
```

**Comment by rhwong** [comment]
同样问题

**Comment by rhwong** [comment]
> 如果你是用的 OpenShamrock
> 
> https://github.com/whitechi73/OpenShamrock/blob/39120bdeaec2efe69905175f1cf966f5a4e1d268/xposed/src/main/java/moe/fuqiuluo/shamrock/remote/HTTPServer.kt#L67-L70

go-cqhttp可以使用，fpv无法连接。
没看懂这里的意思，是需要修改osr吗大佬？
