### ISSUE TITLE
下载协议失败

### ISSUE THREAD

**Issue by iconFehu** [cssxsh/fix-protocol-version#93]
### 问题描述

在同步协议新版本的时候出现错误

### 复现

打开mcl直接同步协议

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

### 签名服务

fix-protocol-version-1.13.0.mirai2

### 系统日志

```plain text
> /protocol sync ANDROID_PHONE 8.9.96
2023-12-30 10:11:13 W/fix-protocol-version: java.lang.IllegalStateException: 从 https://raw.githubusercontent.com/RomiChan/protocol-versions/master/android_phone/8.9.96.json 下载协议失败
java.lang.IllegalStateException: 从 https://raw.githubusercontent.com/RomiChan/protocol-versions/master/android_phone/8.9.96.json 下载协议失败
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.FixProtocolVersion.fetch(FixProtocolVersion.kt:323)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.FixProtocolVersionCommand.fetch(FixProtocolVersionCommand.kt:15)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/RomiChan/protocol-versions/master/android_phone/8.9.96.json
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.FixProtocolVersion.fetch(FixProtocolVersion.kt:298)
        ... 26 more
        Suppressed: java.net.SocketException: Connection reset
                at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
                at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
                at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
                at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
                at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
                at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
                at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
                at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
                at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
                at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
                at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
                at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
                at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
                at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
                at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.FixProtocolVersion.fetch(FixProtocolVersion.kt:307)
                ... 26 more

出现错误
```
```


### 网络日志

_No response_

### 补充信息

_No response_

**Comment by iconFehu** [comment]
目前手动替换了android_phone.json。
请问可以自行修改获取此版本信息的源地址嘛

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/commit/bbe074a2df210ed62ad60ae67b5eaf47c9f4bd4b

**Comment by xyjandyyk** [comment]
老哥你是怎么手动替换的，我找半天没找到替换的地方

**Comment by iconFehu** [comment]
> 老哥你是怎么手动替换的，我找半天没找到替换的地方

告诉你个秘密我把协议更新到最新后，号被冻结了2个了

**Comment by xyjandyyk** [comment]
> > 老哥你是怎么手动替换的，我找半天没找到替换的地方
> 
> 告诉你个秘密我把协议更新到最新后，号被冻结了2个了

哈人，早知道我不手贱重启了

**Comment by iconFehu** [comment]
@cssxsh 老是冻结qq号肿么办 T——T
